discourse_instant_search:
  instant_search_enabled:
    default: true
    client: true
  typesense_nodes:
    client: true
    default: '[{ "host": "localhost", "port": 8108, "protocol": "http"}]'
    json_schema: InstantSearch::SiteSettings::TypesenseNodesJsonSchema
  typesense_api_key:
    client: false
    default: ""
  typesense_read_only_key:
    client: false
    hidden: true
    default: ""
  include_embeddings: false
  index_private_content: false
  proxy_typesense_requests:
    client: true
    default: false
